export const UPDATE_USER = "UPDATE_USER";
export const REMOVE_USER = "REMOVE_USER";


export const TOGGLE_PICTURE_PICKER = "TOGGLE_PICTURE_PICKER";
export const STORE_PICTURE_TO_CROP = "STORE_PICTURE_TO_CROP";
export const REMOVE_PICTURE_TO_CROP = "REMOVE_PICTURE_TO_CROP";
export const STORE_PICTURE_CROPPED = "STORE_PICTURE_CROPPED";