export const TOGGLE_TRACKING = "TOGGLE_TRACKING";

export const UPDATE_USER = "UPDATE_USER";
export const REMOVE_USER = "REMOVE_USER";

export const TOGGLE_PICTURE_PICKER = "TOGGLE_PICTURE_PICKER";
export const STORE_PICTURE_TO_CROP = "STORE_PICTURE_TO_CROP";
export const REMOVE_PICTURE_TO_CROP = "REMOVE_PICTURE_TO_CROP";
export const STORE_PICTURE_CROPPED = "STORE_PICTURE_CROPPED";

export const CHANGE_STAGE = "CHANGE_STAGE";
export const ADD_ONBOARDING_PROPERTIES = "ADD_ONBOARDING_PROPERTIES";
export const TOGGLE_REGISTERING = "TOGGLE_REGISTERING";

export const SET_MENTORS = "SET_MENTORS";
export const SET_RELATIONSHIPS = "SET_RELATIONSHIPS";
export const SET_MENTEES = "SET_MENTEES";
export const SET_PROGRAM_FILTER = "SET_PROGRAM_FILTER";

export const TOGGLE_ADMIN_FETCHING = "TOGGLE_ADMIN_FETCHING";
export const SET_ACTIVE_MENTOR_APPROVAL_ID = "SET_ACTIVE_MENTOR_APPROVAL_ID";
export const SET_ACTIVE_MENTEE_APPROVAL_ID = "SET_ACTIVE_MENTEE_APPROVAL_ID";

export const SET_MATCHING_ID = "SET_MATCHING_ID";
export const SWITCH_MATCHING_MODE = "SWITCH_MATCHING_MODE";
export const SET_MENTOR_RECOMMENDATIONS = "SET_MENTOR_RECOMMENDATIONS";
export const SHOW_MATCHING_CONFIRMATION = "SHOW_MATCHING_CONFIRMATION";
export const UNSET_MATCHING_CONFIRMATION = "UNSET_MATCHING_CONFIRMATION";

export const TOGGLE_MESSAGING_CONNECTED = "TOGGLE_MESSAGING_CONNECTED";
export const ADD_MESSAGING_CHAT = "ADD_MESSAGING_CHAT";
export const SET_ACTIVE_CHAT = "SET_ACTIVE_CHAT";
export const ADD_MESSAGES_TO_CHAT = "ADD_MESSAGES_TO_CHAT";
export const CLEAR_CHATS = "CLEAR_CHATS";

export const SENT_LOGIN_EMAIL = "SENT_LOGIN_EMAIL";
export const UNSET_LOGIN_EMAIL = "SENT_LOGIN_EMAIL";

export const SET_ACTIVE_JOURNEY_MODULE = "SET_ACTIVE_JOURNEY_MODULE";

export const SET_GETTING_STARTED_PROGRESS = "SET_GETTING_STARTED_PROGRESS";
export const TOGGLE_APPROVAL_MODAL = "TOGGLE_APPROVAL_MODAL";
export const SET_MENTOR_APPROVAL_PROPERTIES = "SET_MENTOR_APPROVAL_PROPERTIES";

export const TOGGLE_MENTEE_HOME_MODAL = "TOGGLE_MENTEE_HOME_MODAL";
export const SET_MENTEE_APPROVAL_PROPERTIES = "SET_MENTEE_APPROVAL_PROPERTIES";

export const TOGGLE_ADMIN_MODAL = "TOGGLE_ADMIN_MODAL";
export const TOGGLE_SHOW_MATCHING_DETAILS_MODAL = "TOGGLE_SHOW_MATCHING_DETAILS_MODAL";
export const TOGGLE_MENTOR_CONFIRM_DECISION = "TOGGLE_MENTOR_CONFIRM_DECISION";

export const TOGGLE_DASHBOARD_CONFIRMATION = "TOGGLE_DASHBOARD_CONFIRMATION";

export const SET_PUBLIC_PROFILE = "SET_PUBLIC_PROFILE";
export const UNSET_PUBLIC_PROFILE = "UNSET_PUBLIC_PROFILE";

export const RESET_APP = "RESET_APP";


