export const UPDATE_USER = "UPDATE_USER";
export const REMOVE_USER = "REMOVE_USER";

export const TOGGLE_PICTURE_PICKER = "TOGGLE_PICTURE_PICKER";
export const STORE_PICTURE_TO_CROP = "STORE_PICTURE_TO_CROP";
export const REMOVE_PICTURE_TO_CROP = "REMOVE_PICTURE_TO_CROP";
export const STORE_PICTURE_CROPPED = "STORE_PICTURE_CROPPED";

export const CHANGE_STAGE = "CHANGE_STAGE";
export const ADD_ONBOARDING_PROPERTIES = "ADD_ONBOARDING_PROPERTIES";
export const TOGGLE_REGISTERING = "TOGGLE_REGISTERING";

export const SET_MENTORS = "SET_MENTORS";
export const SET_RELATIONSHIPS = "SET_RELATIONSHIPS";
export const SET_MENTEES = "SET_MENTEES";

export const TOGGLE_ADMIN_FETCHING = "TOGGLE_ADMIN_FETCHING";
export const SET_ACTIVE_MENTOR_APPROVAL_ID = "SET_ACTIVE_MENTOR_APPROVAL_ID";
